# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tms2.proto\"\x07\n\x05\x45mpty\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\tResponse1\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"\x1d\n\tResponse2\x12\x10\n\x08is_found\x18\x01 \x01(\t2R\n\x0f\x46ileFindService\x12 \n\nlist_files\x12\x06.Empty\x1a\n.Response1\x12\x1d\n\x08get_file\x12\x05.Name\x1a\n.Response2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ms2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=13
  _EMPTY._serialized_end=20
  _NAME._serialized_start=22
  _NAME._serialized_end=42
  _RESPONSE1._serialized_start=44
  _RESPONSE1._serialized_end=70
  _RESPONSE2._serialized_start=72
  _RESPONSE2._serialized_end=101
  _FILEFINDSERVICE._serialized_start=103
  _FILEFINDSERVICE._serialized_end=185
# @@protoc_insertion_point(module_scope)
